const MOVIE_CHANGE_LOADING_BAR_PROGRESS = 'MOVIE_CHANGE_LOADING_BAR_PROGRESS';
const MOVIE_LIST_REQUEST_START = 'MOVIE_LIST_REQUEST_START';
const MOVIE_LIST_REQUEST_SUCCESS = 'MOVIE_LIST_REQUEST_SUCCESS';
const MOVIE_LIST_REQUEST_FAILURE = 'MOVIE_LIST_REQUEST_FAILURE';
const MOVIE_DELETE_START = 'MOVIE_DELETE_START';
const MOVIE_DELETE_SUCCESS = 'MOVIE_DELETE_SUCCESS';
const MOVIE_DELETE_FAILURE = 'MOVIE_DELETE_FAILURE';
const MOVIE_SET_DATA_IN_STORE_TRUE = 'MOVIE_SET_DATA_IN_STORE_TRUE';
const MOVIE_ADD_TO_DELETE = 'MOVIE_ADD_TO_DELETE';
const MOVIE_REMOVE_FROM_TO_DELETE = 'MOVIE_REMOVE_FROM_TO_DELETE';
const MOVIE_ADD_GENRE_FILTER = 'MOVIE_ADD_GENRE_FILTER';
const MOVIE_REMOVE_GENRE_FILTER = 'MOVIE_REMOVE_GENRE_FILTER';
const MOVIE_SORT = 'MOVIE_SORT';
const MOVIE_ADD_NEW_MOVIE_START = 'MOVIE_ADD_NEW_MOVIE_START';
const MOVIE_ADD_NEW_MOVIE_SUCCESS = 'MOVIE_ADD_NEW_MOVIE_SUCCESS';
const MOVIE_ADD_NEW_MOVIE_FAILURE = 'MOVIE_ADD_NEW_MOVIE_FAILURE';
const MOVIE_EDIT_START = 'MOVIE_EDIT_START';
const MOVIE_EDIT_SUCCESS = 'MOVIE_EDIT_SUCCESS';
const MOVIE_EDIT_FAILURE = 'MOVIE_EDIT_FAILURE';
const MOVIE_GET_ONE_MOVIE_START = 'MOVIE_GET_ONE_MOVIE_START';
const MOVIE_GET_ONE_MOVIE_SUCCESS = 'MOVIE_GET_ONE_MOVIE_SUCCESS';
const MOVIE_GET_ONE_MOVIE_FAILURE = 'MOVIE_GET_ONE_MOVIE_FAILURE';
const MOVIE_GET_ACTORS_START = 'MOVIE_GET_ACTORS_START';
const MOVIE_GET_ACTORS_SUCCESS = 'MOVIE_GET_ACTORS_SUCCESS';
const MOVIE_GET_ACTORS_FAILURE = 'MOVIE_GET_ACTORS_FAILURE';
const MOVIE_ACTOR_ADD_TO_DELETE = 'MOVIE_ACTOR_ADD_TO_DELETE';
const MOVIE_ACTOR_REMOVE_FROM_TO_DELETE = 'MOVIE_ACTOR_REMOVE_FROM_TO_DELETE';
const MOVIE_DELETE_ACTOR_START = 'MOVIE_DELETE_ACTOR_START';
const MOVIE_DELETE_ACTOR_SUCCESS = 'MOVIE_DELETE_ACTOR_SUCCESS';
const MOVIE_DELETE_ACTOR_FAILURE = 'MOVIE_DELETE_ACTOR_FAILURE';
const MOVIE_ADD_ACTOR_START = 'MOVIE_ADD_ACTOR_START';
const MOVIE_ADD_ACTOR_SUCCESS = 'MOVE_ADD_ACTOR_SUCCESS';
const MOVIE_ADD_ACTOR_FAILURE = 'MOVIE_ADD_ACTOR_FAILURE';
const MOVIE_CHANGE_DIRECTOR_START = 'MOVIE_CHANGE_DIRECTOR_START';
const MOVIE_CHANGE_DIRECTOR_SUCCESS = 'MOVIE_CHANGE_DIRECTOR_SUCCESS';
const MOVIE_CHANGE_DIRECTOR_FAILURE = 'MOVIE_CHANGE_DIRECTOR_FAILURE';
const MOVIE_CHANGE_DIRECTOR_FILTER = 'MOVIE_CHANGE_DIRECTOR_FILTER';
const MOVIE_CHANGE_TITLE_FILTER = 'MOVIE_CHANGE_TITLE_FILTER';

const types = {
    MOVIE_CHANGE_LOADING_BAR_PROGRESS,
    MOVIE_LIST_REQUEST_START,
    MOVIE_LIST_REQUEST_SUCCESS,
    MOVIE_LIST_REQUEST_FAILURE,
    MOVIE_SET_DATA_IN_STORE_TRUE,
    MOVIE_ADD_TO_DELETE,
    MOVIE_REMOVE_FROM_TO_DELETE,
    MOVIE_ADD_GENRE_FILTER,
    MOVIE_REMOVE_GENRE_FILTER,
    MOVIE_SORT,
    MOVIE_DELETE_START,
    MOVIE_DELETE_SUCCESS,
    MOVIE_DELETE_FAILURE,
    MOVIE_ADD_NEW_MOVIE_START,
    MOVIE_ADD_NEW_MOVIE_SUCCESS,
    MOVIE_ADD_NEW_MOVIE_FAILURE,
    MOVIE_EDIT_START,
    MOVIE_EDIT_SUCCESS,
    MOVIE_EDIT_FAILURE,
    MOVIE_GET_ONE_MOVIE_START,
    MOVIE_GET_ONE_MOVIE_SUCCESS,
    MOVIE_GET_ONE_MOVIE_FAILURE,
    MOVIE_GET_ACTORS_START,
    MOVIE_GET_ACTORS_SUCCESS,
    MOVIE_GET_ACTORS_FAILURE,
    MOVIE_ACTOR_ADD_TO_DELETE,
    MOVIE_ACTOR_REMOVE_FROM_TO_DELETE,
    MOVIE_DELETE_ACTOR_START,
    MOVIE_DELETE_ACTOR_SUCCESS,
    MOVIE_DELETE_ACTOR_FAILURE,
    MOVIE_ADD_ACTOR_START,
    MOVIE_ADD_ACTOR_SUCCESS,
    MOVIE_ADD_ACTOR_FAILURE,
    MOVIE_CHANGE_DIRECTOR_START,
    MOVIE_CHANGE_DIRECTOR_SUCCESS,
    MOVIE_CHANGE_DIRECTOR_FAILURE,
    MOVIE_CHANGE_DIRECTOR_FILTER,
    MOVIE_CHANGE_TITLE_FILTER
}

export default types;