const PERSON_LIST_REQUEST_START = 'PERSON_LIST_REQUEST_START';
const PERSON_LIST_REQUEST_SUCCESS = 'PERSON_LIST_REQUEST_SUCCESS';
const PERSON_LIST_REQUEST_FAILURE = 'PERSON_LIST_REQUEST_FAILURE';
const PERSON_ADD_TO_DELETE = 'PERSON_ADD_TO_DELETE';
const PERSON_REMOVE_FROM_TO_DELETE = 'PERSON_REMOVE_FROM_TO_DELETE';
const PERSON_DELETE_START = 'PERSON_DELETE_START';
const PERSON_DELETE_SUCCESS = 'PERSON_DELETE_SUCCESS';
const PERSON_DELETE_FAILURE = 'PERSON_DELETE_FAILURE';
const PERSON_SORT = 'PERSON_SORT';
const PERSON_CHANGE_SORT_TYPE = 'PERSON_CHANGE_SORT_TYPE';//NIE OBSLUZONE
const PERSON_CHANGE_COUNTRY_FILTERS = 'PERSON_CHANGE_COUNTRY_FILTERS';
const PERSON_ADD_NEW_PERSON_START = 'PERSON_ADD_NEW_PERSON_START'
const PERSON_ADD_NEW_PERSON_SUCCESS = 'PERSON_ADD_NEW_PERSON_SUCCESS';
const PERSON_ADD_NEW_PERSON_FAILURE = 'PERSON_ADD_NEW_PERSON_FAILURE';
const PERSON_SET_DATA_IN_STORE_TRUE = 'PERSON_SET_DATA_IN_STORE_TRUE';
const PERSON_CHANGE_LOADING_BAR_PROGRESS = 'PERSON_CHANGE_LOADING_BAR_PROGRESS';
const PERSON_GET_ONE_PERSON_START = 'PERSON_GET_ONE_PERSON_START';
const PERSON_GET_ONE_PERSON_SUCCESS = 'PERSON_GET_ONE_PERSON_SUCCESS';
const PERSON_GET_ONE_PERSON_FAILURE = 'PERSON_GET_ONE_PERSON_FAILURE';
const PERSON_EDIT_START = 'PERSON_EDIT_START';
const PERSON_EDIT_SUCCESS = 'PERSON_EDIT_SUCCESS';
const PERSON_EDIT_FAILURE = 'PERSON_EDIT_FAILURE';
const PERSON_CHANGE_PERIOD_FILTER = 'PERSON_CHANGE_PERIOD_FILTER';
const PERSON_CHANGE_NAME_FILTER = 'PERSON_CHANGE_NAME_FILTER'

const types = {
    PERSON_LIST_REQUEST_START,
    PERSON_LIST_REQUEST_SUCCESS,
    PERSON_LIST_REQUEST_FAILURE,
    PERSON_ADD_TO_DELETE,
    PERSON_REMOVE_FROM_TO_DELETE,
    PERSON_DELETE_START,
    PERSON_DELETE_SUCCESS,
    PERSON_DELETE_FAILURE,
    PERSON_SORT,
    PERSON_CHANGE_SORT_TYPE,
    PERSON_CHANGE_COUNTRY_FILTERS,
    PERSON_ADD_NEW_PERSON_START,
    PERSON_ADD_NEW_PERSON_SUCCESS,
    PERSON_ADD_NEW_PERSON_FAILURE,
    PERSON_SET_DATA_IN_STORE_TRUE,
    PERSON_CHANGE_LOADING_BAR_PROGRESS,
    PERSON_GET_ONE_PERSON_START,
    PERSON_GET_ONE_PERSON_SUCCESS,
    PERSON_GET_ONE_PERSON_FAILURE,
    PERSON_EDIT_START,
    PERSON_EDIT_SUCCESS,
    PERSON_EDIT_FAILURE,
    PERSON_CHANGE_PERIOD_FILTER,
    PERSON_CHANGE_NAME_FILTER
}

export default types;